project_id = "bvwenbgiucjknbpbrght"

[functions.send-revision-notification]
verify_jwt = true

[functions.password-reset-questions]
verify_jwt = false

[functions.verify-admin-password]
verify_jwt = true

[functions.test-admin-secret]
verify_jwt = false
