// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aixuqsimpqiycwyiqnob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpeHVxc2ltcHFpeWN3eWlxbm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDE4MDEsImV4cCI6MjA2OTM3NzgwMX0.I4w7kijVci0a--Ex7gwK56zci12cO_mTapy_y0ly5Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});